spring:
  application:
    name: metric-server

  datasource:
    url:
    username:
    password:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      # update: створює/оновлює таблиці автоматично (добре для розробки)
      # validate: лише перевіряє схему (рекомендовано для продакшну)
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

mqtt:
  client-id:
  host-name:
  certificate-path:
  private-key-path:
  subscribe:
    topic: